name: Test all templates
on: pull_request

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.13.x
          cache: yarn

      - name: Install dependencies
        working-directory: ./packages/create-react-native-library
        run: |
          yarn install --frozen-lockfile

      - name: Build package
        working-directory: ./packages/create-react-native-library
        run: |
          yarn prepare

  check-example:
    runs-on: ubuntu-latest
    needs: [build-package]
    steps:
      - name: Check directory
        working-directory: ./packages/create-react-native-library/
        run: |
          ls -la

      - name: Create example app
        working-directory: ./packages/create-react-native-library/bin
        run: |
          ./create-react-native-library test --slug test --description test --author-name test --author-email test@test --author-url https:// --repo-url https://
